# Generated by Django 4.0.2 on 2022-06-12 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=100)),
                ('git_repo', models.CharField(max_length=100)),
                ('collaborators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=300)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close'), ('MERGED', 'Merged')], default='OPEN', max_length=6)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='git.project')),
            ],
        ),
    ]
