# Generated by Django 4.0.2 on 2022-07-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0005_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_closed',
            field=models.DateTimeField(null=True),
        ),
    ]
