# Generated by Django 4.0.2 on 2022-07-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='git.milestone'),
        ),
    ]
