# Generated by Django 4.0.2 on 2022-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0014_commit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='state',
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
